AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  self-service-portal

  Self-service portal template
Parameters:
  Stage:
    Type: String
    Default: dev
  TableName:
    Type: String
    Default: 'self-service-events-table'

Globals:
  Function:
    Timeout: 3

Resources:
  SelfServicePortalApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SelfServicePortalApi
      StageName: !Ref Stage
      Models:
        Unit:
          type: object
          required:
            - unit
          properties:
            unit:
              type: string
        EventModel:
          type: object
          required:
            - unit
            - name
            - schema
          properties:
            unit:
              type: string
            name:
              type: string
            description:
              type: string
            schema:
              type: object

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_event/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TableName: !Join ["-", [!Ref Stage, !Ref TableName]]
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /events
            Method: post
            RequestModel:
              Model: EventModel
              Required: true
              ValidateBody: true
            RestApiId: !Ref SelfServicePortalApi
      Policies:
      - Statement:
          - Sid: SSMCreateSchemasPolicy
            Effect: Allow
            Action:
              - schemas:CreateSchema
            Resource: !Sub "arn:aws:schemas:${AWS::Region}:${AWS::AccountId}:schema/*.events/*"
          - Sid: SSMPutItemStoragePolicy
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !Join ["/", [!Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table", !Join ["-", [!Ref Stage, !Ref TableName]]]]

  SubscribeToEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscribe_to_event/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SubscribeToEvent:
          Type: Api
          Properties:
            Path: /subscriptions/{eventName}/{eventVersion}
            Method: post
            RequestModel:
              Model: Unit
              Required: true
              ValidateBody: true
            RestApiId: !Ref SelfServicePortalApi

  GetAllEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_events/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetAllEvents:
          Type: Api
          Properties:
            Path: /events/{unit}
            Method: get
            RestApiId: !Ref SelfServicePortalApi

  SelfServiceEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: !Join ["-", [!Ref Stage, !Ref TableName]]

Outputs:
  SelfServicePortalApi:
    Description: "API Gateway endpoint URL for dev stage for self-service portal API"
    Value: !Sub "https://${SelfServicePortalApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  CreateEventFunction:
    Description: "Create event Lambda Function ARN"
    Value: !GetAtt CreateEventFunction.Arn
  CreateEventFunctionIamRole:
    Description: "Implicit IAM Role created for Create Event function"
    Value: !GetAtt CreateEventFunctionRole.Arn
  SubscribeToEventFunction:
    Description: "Subscribe to event Function ARN"
    Value: !GetAtt SubscribeToEventFunction.Arn
  SubscribeToEventFunctionIamRole:
    Description: "Implicit IAM Role created for Subscribe to Event function"
    Value: !GetAtt SubscribeToEventFunctionRole.Arn
  GetAllEventsFunction:
    Description: "Get all the events Funtion ARN"
    Value: !GetAtt GetAllEventsFunction.Arn
  GetAllEventsFunctionIamRole:
    Description: "Implicit IAM Role created for Get all the events function"
    Value: !GetAtt GetAllEventsFunctionRole.Arn
  SelfServiceEventsTable:
    Description: "Self Service API datastore"
    Value: !GetAtt SelfServiceEventsTable.Arn
  SelfServiceEventsTableName:
    Description: "Self Service API datastore name"
    Value: !Join ["-", [!Ref Stage, !Ref TableName]]